### ISSUE TITLE
when doing /help and when starting the bot i get this

### ISSUE THREAD

**Issue by ghost** [L0SER8228/snowsgiving-bot#4]
{
  error: DiscordAPIError: Invalid Form Body
  data.components[0].components[0].url: Scheme "1049723682815225926/1050143574827737219" is not supported. Scheme must be one of ('http', 'https', 'discord').
      at RequestHandler.execute (C:\Users\purpe\Downloads\snowsgiving-bot-main\snowsgiving-bot-main\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RequestHandler.push (C:\Users\purpe\Downloads\snowsgiving-bot-main\snowsgiving-bot-main\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
      at async CommandInteraction.reply (C:\Users\purpe\Downloads\snowsgiving-bot-main\snowsgiving-bot-main\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5)
      at async execute (C:\Users\purpe\Downloads\snowsgiving-bot-main\snowsgiving-bot-main\src\events\interaction\interactionCreate.js:16:7) {
    method: 'post',
    path: '/interactions/1050829806050226267/aW50ZXJhY3Rpb246MTA1MDgyOTgwNjA1MDIyNjI2NzpoSWxXdmMxV0NlMXBxQ21RT0pmdWF5Zmt5U0t0V2VkYVZTRjcxQzd4RnlXVUhhZkFsb3JlVjJaaHVwb2liOUNnZHRpRVJ6RzAzSmZobElVa1RQcDcxcmNpdDBpRUxqempCRHJ0d0NlTjA4SjlYSXN6TFdoMmRpWGEyb09PT1kxNg/callback',
    code: 50035,
    httpStatus: 400,
    requestData: { json: [Object], files: [] }
  }
}
DiscordAPIError: 404: Not Found
    at RequestHandler.execute (C:\Users\purpe\Downloads\snowsgiving-bot-main\snowsgiving-bot-main\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Users\purpe\Downloads\snowsgiving-bot-main\snowsgiving-bot-main\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async ChannelManager.fetch (C:\Users\purpe\Downloads\snowsgiving-bot-main\snowsgiving-bot-main\node_modules\discord.js\src\managers\ChannelManager.js:115:18)
    at async Object.sendErrorLog (C:\Users\purpe\Downloads\snowsgiving-bot-main\snowsgiving-bot-main\src\modules\utils.js:107:8) {
  method: 'get',
  path: '/channels/1049723682815225926/1050143574827737219',
  code: 0,
  httpStatus: 404,
  requestData: { json: undefined, files: [] }
}

**Comment by ghost** [comment]
also when i actually hit someone the image wont load
